# Generated by Django 5.2.11 on 2026-02-19 22:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folio',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, help_text='Users (Caissiers) who can access and work on this folio', related_name='assigned_folios', to=settings.AUTH_USER_MODEL),
        ),
    ]
