# Generated by Django 5.2.11 on 2026-03-05 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasury_api', '0002_folio_assigned_users'),
    ]

def update_saisie_roles(apps, schema_editor):
    User = apps.get_model('treasury_api', 'User')
    User.objects.filter(role__in=['SAISIE_CLIENT', 'SAISIE_FOURNISSEUR']).update(role='SAISIE_FACTURE')

def revert_saisie_roles(apps, schema_editor):
    # This cannot be cleanly reverted since we don't know who was what before.
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('treasury_api', '0002_folio_assigned_users'),
    ]

    operations = [
        migrations.RunPython(update_saisie_roles, revert_saisie_roles),
    ]
